# -*- coding: utf-8 -*-
"""
/***************************************************************************
 GpkgTools
                                 A QGIS plugin
 Es un complemento diseñado para simplificar el manejo de GeoPackages
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-09-26
        copyright            : (C) 2025 by Kevin Irias
        email                : kevin.irias.47@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load GpkgTools class from file GpkgTools.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .gpkg_tools import GpkgTools
    return GpkgTools(iface)
